import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.scss'
import CsrfTokenProvider from '@auth/components/CsrfTokenProvider'
import Header from '@layout/components/header/header'
import StoreProvider from '@layout/components/StoreProvider'
import getCsrfTokenFromHeaders from '@auth/helpers/get-csrf-token-from-headers'
import getUserDataFromSession from '@auth/helpers/get-user-data-from-session'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const csrfToken = getCsrfTokenFromHeaders()
  let user = await getUserDataFromSession()
  console.log('**********in root layout')
  return (
    <html lang="en">
      <body className={inter.variable}>
        <CsrfTokenProvider csrfToken={csrfToken}>
          <StoreProvider user={user}>
            <Header />
            {children}
          </StoreProvider>
        </CsrfTokenProvider>
      </body>
    </html>
  )
}
