import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.scss'
import { cookies, headers } from 'next/headers'
import CsrfTokenProvider from '@auth/components/CsrfTokenProvider'
import Header from '@layout/components/header/header'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const csrfToken = headers().get('csrfToken')
  if (!csrfToken) throw new Error('csrfToken cookie is not set')

  return (
    <html lang="en">
      <body className={inter.variable}>
        <Header />
        <CsrfTokenProvider csrfToken={csrfToken}>{children}</CsrfTokenProvider>
      </body>
    </html>
  )
}
