import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.scss'
import { cookies } from 'next/headers'
import CsrfTokenProvider from '@auth/components/CsrfTokenProvider'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const csrfToken = cookies().get('csrfToken')?.value
  if (!csrfToken) throw new Error('csrfToken cookie is not set')

  return (
    <html lang="en">
      <body className={inter.variable}>
        <CsrfTokenProvider csrfToken={csrfToken}>{children}</CsrfTokenProvider>
      </body>
    </html>
  )
}
